version: '3.9'
services:
  sql-praktikum:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ca_db
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-p", "-e", "show schemas"]
      interval: 10s

  docker-go-praktikum:
    image: naufal360/docker-go-praktikum:v1
    environment:
      - DB_HOST=sql-praktikum
    ports:
      - "80:8000"
    restart: on-failure
    depends_on:
      sql-praktikum:
        condition: service_healthy
